### ISSUE TITLE
Not all chits are winning chits

### ISSUE THREAD

**Issue by nitin-taur** [pnkjgupta111/ChristmasGame#1]
https://github.com/pnkjgupta111/ChristmasGame/blob/c0e6fd0c29526ec4b30c8884a98b61779d58c61f/src/main/java/ChristmasGame.java#L37

Only the chits players/guest can win not all.

`public SantaHelper(final List<Chit> chits) {
        this.winningChits = new CopyOnWriteArraySet<>(chits);
    }`

**Comment by pnkjgupta111** [comment]
Hi Nitin,

Not everybody will win as we are removing the chits which are not able to
answer. See here :-

https://github.com/pnkjgupta111/ChristmasGame/blob/c0e6fd0c29526ec4b30c8884a98b61779d58c61f/src/main/java/entities/SantaHelper.java#L31

Regards
Pankaj Gupta
