### ISSUE TITLE
Why winning chit CopyOnWriteArraySet?

### ISSUE THREAD

**Issue by nitin-taur** [pnkjgupta111/ChristmasGame#2]
https://github.com/pnkjgupta111/ChristmasGame/blob/c0e6fd0c29526ec4b30c8884a98b61779d58c61f/src/main/java/entities/SantaHelper.java#L16

Can it be handled better than this? Did you heard of 'happens-before' scenarios (JSR-133) ?  Finalisation guarantees?

**Comment by pnkjgupta111** [comment]
Hi Nitin,

CopyOnWriteArraySet was used here as we are removing elements from the
collection while iterating them.

See here
https://github.com/pnkjgupta111/ChristmasGame/blob/c0e6fd0c29526ec4b30c8884a98b61779d58c61f/src/main/java/entities/SantaHelper.java#L34

I think using an iterator with a normal Hashset should suffice here which
should take care of ConcurrentModificationException.

Regards
Pankaj Gupta
9891425207

**Comment by pnkjgupta111** [comment]
Issue fixed https://github.com/pnkjgupta111/ChristmasGame/commit/17027f06001a4ac851141169217f710ad699d2c6
